# Generated by Django 2.0 on 2018-01-23 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_firstname', models.CharField(default=None, max_length=20, unique=True)),
                ('employee_surname', models.CharField(default=None, max_length=20)),
                ('employee_job_title', models.CharField(default=None, max_length=20)),
                ('date_started', models.DateTimeField(default=None, verbose_name='Date started at Company')),
                ('job_description', models.TextField(default=None, max_length=70)),
                ('employee_image', models.ImageField(blank=True, upload_to='employee_images/')),
            ],
        ),
    ]
