# Generated by Django 2.0 on 2018-01-23 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='employees',
            new_name='Employee',
        ),
    ]
