# Generated by Django 2.0 on 2018-01-31 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffapp', '0003_auto_20180124_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_started',
            field=models.DateField(verbose_name='Date started at Company'),
        ),
    ]
