# Generated by Django 2.0 on 2018-02-02 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffapp', '0005_auto_20180202_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
